name = 'bayt-al-hikmah'
compatibility_date = "2025-03-25"

[build]
command = "npx quartz build" # Adjust this if Quartz has a specific build command

[[services]]
binding = "QUARTZ"
service = "quartz-worker"
