name = 'bayt-al-hikmah'
compatibility_date = "2025-03-25"
main = "index.d.ts"

[build]
command = "npx quartz build" # Adjust this if Quartz has a specific build command

[site]
bucket = "./public"

[[services]]
binding = "QUARTZ"
service = "quartz-worker"
